workflows:
  android-workflow:
    name: "<workflow_display_name>"
    max_build_duration: 60
    environment:
      vars:
        CM_KEYSTORE: >-
          Encrypted(<KEYSTORE_FILE>)
        CM_KEYSTORE_PASSWORD: >-
          Encrypted(<KEYSTORE_PASSWORD>)
        CM_KEY_ALIAS_PASSWORD: >-
          Encrypted(<KEYSTORE_ALIAS>)
        CM_KEY_ALIAS_USERNAME: >-
          Encrypted(<KEYSTORE_ALIAS_USERNAME>)
        node: latest
    triggering:
      events:
        - push
      branch_pattern:
        - pattern: "*master*"
          include: true
          source: true
    scripts:
      - name: Install NPM and Build
        script: |
          npm install --quiet --no-optional
          npm run build
          ionic info
          ionic deploy manifest
          ionic capacitor sync android --no-build
      - name: Setup local properties
        script: |
          echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
      - name: Setup keystore
        script: |
          #!/bin/sh
          echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
          cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_ALIAS_PASSWORD
          keyAlias=$CM_KEY_ALIAS_USERNAME
          storeFile=/tmp/keystore.keystore
          EOF
      - name: Build Android app
        script: |
          cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/**/*.apk
    publishing:
      google_play:
        credentials: >-
          Encrypted(<SERVICE_ACCOUNT_CREDENTIAL_FILE>)
        track: alpha
      email:
        recipients:
          - <AN_EMAIL_ADDRESS>
